"use client";
import {useEffect,useState} from "react";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Plus,Upload,Eye,Save,RefreshCw} from "lucide-react";
import {entrySchema} from "@/lib/validation";
import type {Entry} from "@/lib/content";
type Draft=Omit<Entry,"id">&{id?:string};
function blank(kind:"episode"|"news"):Draft{return{kind,title:"",summary:"",body:"",cover:"",video_url:"",published:0,date:new Date().toISOString().slice(0,10),revision:0}}
export default function Editor(){const[kind,setKind]=useState<"episode"|"news">("episode");const[rows,setRows]=useState<Entry[]>([]);const[draft,setDraft]=useState<Draft|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[preview,setPreview]=useState(false);const[dirty,setDirty]=useState(false);const[pending,setPending]=useState<Draft|null>(null);
async function reload(){setLoading(true);try{const r=await fetch("/api/entries",{cache:"no-store"});const j=await r.json() as {error?:string;entries:Entry[]};if(!r.ok)throw Error(j.error);setRows(j.entries);setError("")}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
useEffect(()=>{void reload()},[]);
useEffect(()=>{if(!dirty)return;const prevent=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",prevent);return()=>window.removeEventListener("beforeunload",prevent)},[dirty]);
useEffect(()=>{const mc=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(mc.registerTool({name:"stage_nanobots_article",title:"Подготовить материал",description:"Заполняет форму новой серии или новости для проверки редактором. Не сохраняет и не публикует.",inputSchema:{type:"object",properties:{kind:{type:"string",enum:["episode","news"]},title:{type:"string"},summary:{type:"string"},body:{type:"string"},video_url:{type:"string"}},required:["kind","title"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(dirty)throw Error("Сначала сохраните текущий материал");if(!input||typeof input!=="object")throw Error("Нужен объект");const value=input as Record<string,unknown>;if(value.kind!=="episode"&&value.kind!=="news")throw Error("Неизвестный тип материала");const parsed=entrySchema.safeParse({...blank(value.kind),...value});if(!parsed.success)throw Error(parsed.error.issues[0].message);setKind(parsed.data.kind);setDraft(parsed.data);setDirty(true);return{staged:true,published:false}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[dirty]);
function start(d:Draft){if(dirty){setPending(d);return}setDraft(d);setError("");setNotice("");setDirty(false)}
function change(field:keyof Draft,value:string){setDraft(d=>d?{...d,[field]:value}:d);setDirty(true);setNotice("")}
async function save(published:0|1){if(!draft)return;const value={...draft,published};const parsed=entrySchema.safeParse(value);if(!parsed.success){setError(parsed.error.issues[0].message);return}setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/entries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const j=await r.json() as {error?:string;entry:Entry};if(!r.ok)throw Error(j.error);setDraft(j.entry);setRows(old=>[j.entry,...old.filter(e=>e.id!==j.entry.id)].sort((a,b)=>b.date.localeCompare(a.date)));setDirty(false);setNotice(published?"Материал опубликован на сайте.":"Черновик сохранён. На сайте он не отображается.")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function upload(file?:File){if(!file)return;if(file.size>10*1024*1024){setError("Максимальный размер обложки — 10 МБ");return}setBusy(true);setError("");try{const form=new FormData();form.set("file",file);const r=await fetch("/api/upload",{method:"POST",body:form});const j=await r.json() as {error?:string;url:string};if(!r.ok)throw Error(j.error);change("cover",j.url)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <><h1 className="admin-title">Серии и новости</h1><div className="admin-toolbar"><Tabs value={kind} onValueChange={v=>setKind(v as "episode"|"news")}><TabsList><TabsTrigger value="episode">Серии</TabsTrigger><TabsTrigger value="news">Новости</TabsTrigger></TabsList></Tabs><button className="cta small" disabled={busy} onClick={()=>start(blank(kind))}><Plus size={18}/> {kind==="episode"?"Добавить серию":"Добавить новость"}</button></div><p>Сохраните материал как черновик или опубликуйте его. Чтобы убрать опубликованный материал с сайта, сохраните его как черновик.</p>{error&&<div role="alert" className="error-message">{error}</div>}{notice&&<p role="status" className="notice">{notice}</p>}{loading?<p role="status">Загружаем материалы…</p>:<div className="admin-list">{rows.filter(e=>e.kind===kind).length===0&&<p>Здесь пока нет {kind==="episode"?"серий":"новостей"}. Добавьте первый материал.</p>}{rows.filter(e=>e.kind===kind).map(e=><article className="admin-row" key={e.id}>{e.cover&&<img src={e.cover} alt=""/>}<div><h3>{e.title}</h3><p>{e.date} · <span className={`status-pill ${e.published?"":"draft"}`}>{e.published?"Опубликовано":"Черновик"}</span></p></div><button className="quiet-button" disabled={busy} onClick={()=>start({...e})}>Редактировать</button></article>)}</div>}<button className="text-link" disabled={busy||loading} onClick={()=>void reload()} style={{marginTop:18}}><RefreshCw size={15}/> Обновить список</button>
{draft&&<form className="editor-form" onSubmit={e=>{e.preventDefault();void save(0)}}><h2 style={{fontSize:28,margin:0}}>{draft.kind==="episode"?"Серия":"Новость"}{draft.id?" · редактирование":" · новый материал"}</h2><label>Название<input value={draft.title} maxLength={180} required onChange={e=>change("title",e.target.value)} disabled={busy}/></label><label>Короткое описание<textarea value={draft.summary} maxLength={500} onChange={e=>change("summary",e.target.value)} disabled={busy}/></label>{draft.kind==="episode"?<label>Ссылка на видео<input type="url" value={draft.video_url} placeholder="https://vk.ru/video…" onChange={e=>change("video_url",e.target.value)} disabled={busy}/></label>:<label>Текст новости<textarea className="long-text" value={draft.body} maxLength={30000} onChange={e=>change("body",e.target.value)} disabled={busy}/></label>}<div className="form-pair"><label>Дата материала<input type="date" required value={draft.date} onChange={e=>change("date",e.target.value)} disabled={busy}/><small>Дата для отображения и сортировки. Публикация происходит сразу.</small></label><label><span><Upload size={16} style={{display:"inline"}}/> Загрузить обложку</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files?.[0])} disabled={busy}/><small>JPG, PNG или WebP, до 10 МБ.</small></label></div><label>Или ссылка на обложку<input value={draft.cover} onChange={e=>change("cover",e.target.value)} placeholder="https://…" disabled={busy}/></label>{draft.cover&&<img src={draft.cover} alt="Предпросмотр обложки" className="editor-cover"/>}<div className="form-actions"><button type="submit" className="quiet-button" disabled={busy}><Save size={16} style={{display:"inline"}}/> Сохранить черновик</button><button type="button" className="quiet-button" onClick={()=>setPreview(true)}><Eye size={16} style={{display:"inline"}}/> Предпросмотр</button><button type="button" className="cta small" disabled={busy} onClick={()=>void save(1)}>{busy?"Сохраняем…":"Опубликовать"}</button></div></form>}
<Dialog open={preview} onOpenChange={setPreview}><DialogContent className="news-modal"><DialogTitle>{draft?.title||"Без названия"}</DialogTitle><DialogDescription>{draft?.summary||"Предпросмотр материала"}</DialogDescription>{draft?.cover&&<img src={draft.cover} alt="Обложка"/>}<div className="article-text">{draft?.body}</div>{draft?.video_url&&/^https:\/\//.test(draft.video_url)&&<a className="cta" href={draft.video_url} target="_blank" rel="noopener noreferrer">Открыть видео</a>}</DialogContent></Dialog>
<Dialog open={!!pending} onOpenChange={open=>!open&&setPending(null)}><DialogContent><DialogTitle>Есть несохранённые изменения</DialogTitle><DialogDescription>Сначала сохраните текущий материал или отбросьте изменения.</DialogDescription><button className="quiet-button" onClick={()=>setPending(null)}>Вернуться к материалу</button><button className="quiet-button" onClick={()=>{setDraft(pending);setPending(null);setDirty(false);setError("");setNotice("")}}>Отбросить изменения</button></DialogContent></Dialog></>}
