"use client";
import {useState} from "react";
import {Play,BookOpen,ArrowUpRight,Menu,Atom,Users,Film,ChevronRight} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import AudienceStats from "@/components/audience-stats";
import Crop from "@/components/crop";
import {characters,organs,socials,type Entry} from "@/lib/content";
export default function HomeClient({entries,unavailable}:{entries:Entry[];unavailable:boolean}){
const [organ,setOrgan]=useState("heart");const[hero,setHero]=useState<number|null>(null);const[news,setNews]=useState<Entry|null>(null);const[menu,setMenu]=useState(false);
const active=organs.find(o=>o.key===organ)!;const episodes=entries.filter(e=>e.kind==="episode");const posts=entries.filter(e=>e.kind==="news");
return <><a className="skip" href="#main">К содержанию</a><header className="nav"><a href="#" aria-label="Наноботы — главная"><Crop src="/art/logo.jpg" box={[1536,1536,161,414,1227,721]} alt="Наноботы" className="brand"/></a><nav aria-label="Главное меню"><a href="#crew">Персонажи</a><a href="#watch">Смотреть</a><a href="#map">Карта тела</a><a href="#schools">Школам</a></nav><a className="cta small" href="#watch"><Play size={17} fill="currentColor"/> Смотреть серии</a><button className="mobile-menu" aria-label="Открыть меню" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu/></button>{menu&&<div className="mobile-links">{[["crew","Персонажи"],["watch","Смотреть"],["map","Карта тела"],["schools","Школам"],["news","Новости"]].map(([id,label])=><a href={`#${id}`} key={id} onClick={()=>setMenu(false)}>{label}</a>)}</div>}</header>
<main id="main"><div className="hero-wrap"><section className="hero" aria-labelledby="hero-title"><img className="hero-poster" src="/art/poster-wide.jpg" alt="Пётр и команда Наноботов — между лабораторией и вселенной внутри тела" fetchPriority="high"/><div className="hero-copy"><span className="eyebrow"><Atom size={18}/> НАУКА С ХАРАКТЕРОМ</span><h1 id="hero-title">Целая вселенная.<br/><em>Внутри тебя!</em></h1><p>Пять наноботов внутри учёного Петра —<br className="desktop"/> и наука становится приключением.</p><div className="hero-actions"><a className="cta" href="#watch"><Play size={18} fill="currentColor"/> Смотреть серии</a><a className="text-link" href="#crew">Кто такие наноботы? <ChevronRight size={19}/></a></div><div className="hero-note">Мультсериал о теле и здоровье для всей семьи</div></div></section></div>
<section className="quick-grid" aria-label="Знакомство с проектом"><a href="#crew" className="quick teal"><Users/><div><h3>Экипаж</h3><p>Пять характеров. Одна команда.</p></div><ArrowUpRight/></a><a href="#watch" className="quick pink"><Film/><div><h3>Смотреть серии</h3><p>Приключения начинаются здесь.</p></div><ArrowUpRight/></a><a href="#schools" className="quick purple"><BookOpen/><div><h3>Школам</h3><p>Открывать новое вместе.</p></div><ArrowUpRight/></a></section>
<section id="crew" className="crew-section"><div className="section-heading"><div><span className="eyebrow">ЗНАКОМЬСЯ С ГЕРОЯМИ</span><h2>Экипаж «Наноботов»</h2></div><p>Маленькие герои с большой миссией:<br/>разобраться, как работает наш организм.</p></div><div className="crew-grid">{characters.map((c,i)=><button key={c.key} className="character" style={{"--hero-color":c.color} as React.CSSProperties} onClick={()=>setHero(i)}><div className="character-art"><Crop src={`/art/${c.key}.jpg`} box={c.box} alt={c.name}/></div><div className="character-label"><h3>{c.name}</h3><p>{c.role}</p><span>Познакомиться <ArrowUpRight size={16}/></span></div></button>)}</div></section>
<section id="map"><div className="body-explorer"><div className="map-left"><span className="eyebrow">ЭКСПЕДИЦИЯ ВНУТРЬ</span><h2>Карта тела Петра</h2><p>Выбери точку — узнай, что внутри.</p><div className="body-picture"><img src="/art/body.png" alt="Силуэт Петра с сердцем и кровеносными сосудами"/>{organs.map(o=><button className={`hotspot ${organ===o.key?"active":""}`} key={o.key} style={{left:`${o.x}%`,top:`${o.y}%`}} onClick={()=>setOrgan(o.key)} aria-label={o.label} aria-pressed={organ===o.key}><span/></button>)}</div></div><div className="map-right"><Tabs value={organ} onValueChange={setOrgan}><TabsList className="organ-tabs">{organs.map(o=><TabsTrigger key={o.key} value={o.key}>{o.title}</TabsTrigger>)}</TabsList></Tabs><article className="organ-card" aria-live="polite"><img src={active.image} alt={active.label}/><div><span className="eyebrow">ИССЛЕДУЕМ ОРГАНИЗМ</span><h3>{active.label}</h3><p>{active.text}</p><a className="text-link" href="#watch">Отправиться в приключение <ChevronRight size={18}/></a></div></article></div></div></section>
<section id="watch"><div className="section-heading"><div><span className="eyebrow">УСТРАИВАЙСЯ ПОУДОБНЕЕ</span><h2>Смотрим «Наноботов»</h2></div><a className="text-link" href={socials[0].url} target="_blank" rel="noopener noreferrer">Наш канал в VK <ArrowUpRight size={18}/></a></div>{unavailable?<div className="notice">Список серий временно недоступен. Смотрите «Наноботов» на наших площадках ниже.</div>:episodes.length?<div className="episode-grid">{episodes.map(e=><a key={e.id} href={e.video_url} target="_blank" rel="noopener noreferrer" className="episode"><div className="episode-image"><img src={e.cover||"/art/adventure.jpg"} alt="" loading="lazy"/><span className="play-badge"><Play fill="currentColor"/></span></div><h3>{e.title}</h3><p>{e.summary}</p></a>)}</div>:<div className="watch-banner"><img src="/art/adventure.jpg" alt="Микра и Эндо исследуют мир внутри тела"/><div><h3>Приключения уже на наших каналах</h3><p>Выбирай любимую площадку и присоединяйся к команде.</p><a className="cta" href={socials[0].url} target="_blank" rel="noopener noreferrer"><Play size={18} fill="currentColor"/> Смотреть в VK</a></div></div>}<div className="watch-platforms">{socials.slice(0,4).map(s=><a key={s.name} href={s.url} target="_blank" rel="noopener noreferrer"><span style={{background:s.color}}>{s.short}</span>{s.name}<ArrowUpRight size={17}/></a>)}</div></section>
<section id="schools"><div className="school-banner"><div><span className="eyebrow">ДЛЯ УЧИТЕЛЕЙ И РОДИТЕЛЕЙ</span><h2>Удивляться. Спрашивать.<br/>Понимать.</h2><p>Наноботы помогают говорить с детьми о теле и здоровье через истории, юмор и открытия.</p><p className="school-status">Уроки и материалы для занятий готовятся к публикации.</p></div><div className="school-art"><Crop src="/art/omni.jpg" box={[1536,1069,370,687,458,365]} alt="Омни"/><span className="school-sticker">Наука<br/>рядом!</span></div></div></section>
<section id="news"><div className="section-heading"><div><span className="eyebrow">ЖИЗНЬ ПРОЕКТА</span><h2>Новости</h2></div><a className="text-link" href="https://t.me/nanobots_mult" target="_blank" rel="noopener noreferrer">Мы в Telegram <ArrowUpRight size={18}/></a></div>{posts.length?<div className="news-grid">{posts.map(n=><button key={n.id} className="news-card" onClick={()=>setNews(n)}>{n.cover&&<img src={n.cover} alt="" loading="lazy"/>}<time>{new Date(n.date).toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric",timeZone:"UTC"})}</time><h3>{n.title}</h3><p>{n.summary}</p><span className="text-link">Читать <ArrowUpRight size={17}/></span></button>)}</div>:<div className="news-empty"><p>{unavailable?"Новости временно недоступны.":"Новые истории, премьеры и жизнь команды — в наших соцсетях."}</p><a href="https://t.me/nanobots_mult" target="_blank" rel="noopener noreferrer">Заглянуть в Telegram <ArrowUpRight size={18}/></a></div>}</section>
<AudienceStats/><section id="partners"><div className="partners"><div><span className="eyebrow">ПАРТНЁРАМ</span><h2>Давайте делать<br/>науку ближе</h2><p>«Наноботы» — анимационный образовательный проект студии ООО «4МЕДС».</p></div><div className="partner-options"><article><Film/><h3>Интеграции</h3><p>Истории и специальные выпуски.</p></article><article><BookOpen/><h3>Образование</h3><p>Совместные проекты для детей и семей.</p></article><article><Users/><h3>Лицензирование</h3><p>Герои за пределами экрана.</p></article></div></div></section>
</main><footer><div className="footer-inner"><div><Crop src="/art/logo.jpg" box={[1536,1536,161,414,1227,721]} alt="Наноботы" className="footer-brand"/><p>Большая наука для маленьких исследователей.</p></div><div><h3>Будем на связи</h3><div className="social-grid">{socials.map(s=><a href={s.url} key={s.name} target="_blank" rel="noopener noreferrer">{s.name}<ArrowUpRight size={14}/></a>)}</div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} «Наноботы» · ООО «4МЕДС»</span><a href="/admin">Редакция сайта</a></div></footer>
<Dialog open={hero!==null} onOpenChange={open=>!open&&setHero(null)}><DialogContent className="character-modal">{hero!==null&&<><Crop src={`/art/${characters[hero].key}.jpg`} box={characters[hero].box} alt={characters[hero].name}/><div><DialogTitle>{characters[hero].name}</DialogTitle><DialogDescription>{characters[hero].role}</DialogDescription><p>{characters[hero].text}</p></div></>}</DialogContent></Dialog>
<Dialog open={!!news} onOpenChange={open=>!open&&setNews(null)}><DialogContent className="news-modal">{news&&<><DialogTitle>{news.title}</DialogTitle><DialogDescription>{news.summary}</DialogDescription>{news.cover&&<img src={news.cover} alt=""/>}<div className="article-text">{news.body}</div></>}</DialogContent></Dialog></>}
